# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bank_pb2 as bank__pb2


class BankOpsStub(object):
  """---- Main API ---- 

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.QueryBalance = channel.unary_unary(
        '/bankops.BankOps/QueryBalance',
        request_serializer=bank__pb2.AccountNo.SerializeToString,
        response_deserializer=bank__pb2.FinanceDetails.FromString,
        )
    self.QueryDetails = channel.unary_unary(
        '/bankops.BankOps/QueryDetails',
        request_serializer=bank__pb2.AccountNo.SerializeToString,
        response_deserializer=bank__pb2.CustomerDetails.FromString,
        )
    self.Deposit = channel.unary_unary(
        '/bankops.BankOps/Deposit',
        request_serializer=bank__pb2.TransferMessage.SerializeToString,
        response_deserializer=bank__pb2.UpdatedAccounts.FromString,
        )


class BankOpsServicer(object):
  """---- Main API ---- 

  """

  def QueryBalance(self, request, context):
    """List of Services

    Services related to Querying of Data

    Retrives Account Balance of a user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def QueryDetails(self, request, context):
    """Retrives Personal details of corresponding account number
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Deposit(self, request, context):
    """Services regards to the withdrawl and deposit of money (Core Business Logic) 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BankOpsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'QueryBalance': grpc.unary_unary_rpc_method_handler(
          servicer.QueryBalance,
          request_deserializer=bank__pb2.AccountNo.FromString,
          response_serializer=bank__pb2.FinanceDetails.SerializeToString,
      ),
      'QueryDetails': grpc.unary_unary_rpc_method_handler(
          servicer.QueryDetails,
          request_deserializer=bank__pb2.AccountNo.FromString,
          response_serializer=bank__pb2.CustomerDetails.SerializeToString,
      ),
      'Deposit': grpc.unary_unary_rpc_method_handler(
          servicer.Deposit,
          request_deserializer=bank__pb2.TransferMessage.FromString,
          response_serializer=bank__pb2.UpdatedAccounts.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'bankops.BankOps', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
