# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bank.proto',
  package='bankops',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nbank.proto\x12\x07\x62\x61nkops\"\x1f\n\tAccountNo\x12\x12\n\nAccount_No\x18\x01 \x01(\t\"C\n\x0e\x46inanceDetails\x12\x12\n\nAccount_No\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0f\n\x07\x42\x61lance\x18\x03 \x01(\x05\"P\n\x0f\x43ustomerDetails\x12\x12\n\nAccount_No\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0b\n\x03\x41ge\x18\x03 \x01(\x05\x12\x0e\n\x06Gender\x18\x04 \x01(\t\"I\n\x0fTransferMessage\x12\x13\n\x0b\x66romAccount\x18\x01 \x01(\t\x12\x11\n\ttoAccount\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\"g\n\x0fUpdatedAccounts\x12\x13\n\x0b\x66romAccount\x18\x01 \x01(\t\x12\x16\n\x0e\x66romAccountBal\x18\x02 \x01(\x05\x12\x11\n\ttoAccount\x18\x03 \x01(\t\x12\x14\n\x0ctoAccountBal\x18\x04 \x01(\x05\x32\xc9\x01\n\x07\x42\x61nkOps\x12=\n\x0cQueryBalance\x12\x12.bankops.AccountNo\x1a\x17.bankops.FinanceDetails\"\x00\x12>\n\x0cQueryDetails\x12\x12.bankops.AccountNo\x1a\x18.bankops.CustomerDetails\"\x00\x12?\n\x07\x44\x65posit\x12\x18.bankops.TransferMessage\x1a\x18.bankops.UpdatedAccounts\"\x00\x62\x06proto3')
)




_ACCOUNTNO = _descriptor.Descriptor(
  name='AccountNo',
  full_name='bankops.AccountNo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Account_No', full_name='bankops.AccountNo.Account_No', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=54,
)


_FINANCEDETAILS = _descriptor.Descriptor(
  name='FinanceDetails',
  full_name='bankops.FinanceDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Account_No', full_name='bankops.FinanceDetails.Account_No', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='bankops.FinanceDetails.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Balance', full_name='bankops.FinanceDetails.Balance', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=123,
)


_CUSTOMERDETAILS = _descriptor.Descriptor(
  name='CustomerDetails',
  full_name='bankops.CustomerDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Account_No', full_name='bankops.CustomerDetails.Account_No', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='bankops.CustomerDetails.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Age', full_name='bankops.CustomerDetails.Age', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Gender', full_name='bankops.CustomerDetails.Gender', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=205,
)


_TRANSFERMESSAGE = _descriptor.Descriptor(
  name='TransferMessage',
  full_name='bankops.TransferMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromAccount', full_name='bankops.TransferMessage.fromAccount', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toAccount', full_name='bankops.TransferMessage.toAccount', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='bankops.TransferMessage.amount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=280,
)


_UPDATEDACCOUNTS = _descriptor.Descriptor(
  name='UpdatedAccounts',
  full_name='bankops.UpdatedAccounts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromAccount', full_name='bankops.UpdatedAccounts.fromAccount', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fromAccountBal', full_name='bankops.UpdatedAccounts.fromAccountBal', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toAccount', full_name='bankops.UpdatedAccounts.toAccount', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toAccountBal', full_name='bankops.UpdatedAccounts.toAccountBal', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=385,
)

DESCRIPTOR.message_types_by_name['AccountNo'] = _ACCOUNTNO
DESCRIPTOR.message_types_by_name['FinanceDetails'] = _FINANCEDETAILS
DESCRIPTOR.message_types_by_name['CustomerDetails'] = _CUSTOMERDETAILS
DESCRIPTOR.message_types_by_name['TransferMessage'] = _TRANSFERMESSAGE
DESCRIPTOR.message_types_by_name['UpdatedAccounts'] = _UPDATEDACCOUNTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountNo = _reflection.GeneratedProtocolMessageType('AccountNo', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTNO,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bankops.AccountNo)
  ))
_sym_db.RegisterMessage(AccountNo)

FinanceDetails = _reflection.GeneratedProtocolMessageType('FinanceDetails', (_message.Message,), dict(
  DESCRIPTOR = _FINANCEDETAILS,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bankops.FinanceDetails)
  ))
_sym_db.RegisterMessage(FinanceDetails)

CustomerDetails = _reflection.GeneratedProtocolMessageType('CustomerDetails', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMERDETAILS,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bankops.CustomerDetails)
  ))
_sym_db.RegisterMessage(CustomerDetails)

TransferMessage = _reflection.GeneratedProtocolMessageType('TransferMessage', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFERMESSAGE,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bankops.TransferMessage)
  ))
_sym_db.RegisterMessage(TransferMessage)

UpdatedAccounts = _reflection.GeneratedProtocolMessageType('UpdatedAccounts', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEDACCOUNTS,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bankops.UpdatedAccounts)
  ))
_sym_db.RegisterMessage(UpdatedAccounts)



_BANKOPS = _descriptor.ServiceDescriptor(
  name='BankOps',
  full_name='bankops.BankOps',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=388,
  serialized_end=589,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryBalance',
    full_name='bankops.BankOps.QueryBalance',
    index=0,
    containing_service=None,
    input_type=_ACCOUNTNO,
    output_type=_FINANCEDETAILS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='QueryDetails',
    full_name='bankops.BankOps.QueryDetails',
    index=1,
    containing_service=None,
    input_type=_ACCOUNTNO,
    output_type=_CUSTOMERDETAILS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Deposit',
    full_name='bankops.BankOps.Deposit',
    index=2,
    containing_service=None,
    input_type=_TRANSFERMESSAGE,
    output_type=_UPDATEDACCOUNTS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BANKOPS)

DESCRIPTOR.services_by_name['BankOps'] = _BANKOPS

# @@protoc_insertion_point(module_scope)
